ALTER TABLE parent
    ADD (token_version NUMBER(10) DEFAULT 0 NOT NULL);

ALTER TABLE student
    ADD (token_version NUMBER(10) DEFAULT 0 NOT NULL);

CREATE TABLE refresh_token
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER NOT NULL,
    role       VARCHAR2(20) NOT NULL,
    token_hash VARCHAR2(128) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked    NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_user ON refresh_token (user_id, role);
