ALTER TABLE parent
    ADD (active NUMBER(1) DEFAULT 1 NOT NULL);

CREATE TABLE admin
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(255) NOT NULL,
    password      VARCHAR2(255) NOT NULL,
    full_name     VARCHAR2(255) NOT NULL,
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_admin_email UNIQUE (email)
);
