-- Textbook library feature (2026-09-05): Admin uploads PDF textbooks organized by
-- Grade -> Subject name -> Curriculum series -> Volume (e.g. "Lop 4 -> Toan tap 1 -> Ket noi tri
-- thuc"). A Parent's own Subject rows can each link to MULTIPLE library documents
-- (subject_library_link is a many-to-many join, see LibraryService's javadoc) - both Parent and
-- Student can then view/download a linked document.
CREATE TABLE library_document
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade        NUMBER(2)     NOT NULL,
    subject_name VARCHAR2(255) NOT NULL,
    curriculum   VARCHAR2(100) NOT NULL,
    volume       VARCHAR2(100),
    title        VARCHAR2(255) NOT NULL,
    file_path    VARCHAR2(255) NOT NULL,
    file_size    NUMBER(19)    NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    created_by   VARCHAR2(100),
    updated_by   VARCHAR2(100),
    deleted      NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE subject_library_link
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id          NUMBER NOT NULL,
    library_document_id NUMBER NOT NULL,
    linked_at           TIMESTAMP,
    linked_by           VARCHAR2(100),

    CONSTRAINT uq_subject_library_link UNIQUE (subject_id, library_document_id),
    CONSTRAINT fk_subject_library_link_subject FOREIGN KEY (subject_id) REFERENCES subject (id),
    CONSTRAINT fk_subject_library_link_document FOREIGN KEY (library_document_id) REFERENCES library_document (id)
);
