CREATE TABLE translate
(
    lang_key VARCHAR2(255) NOT NULL,
    lang     VARCHAR2(20)  NOT NULL,
    value    CLOB,

    CONSTRAINT pk_translate PRIMARY KEY (lang_key, lang)
);

CREATE TABLE parent
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR2(255) NOT NULL,
    email         VARCHAR2(255) NOT NULL,
    password      VARCHAR2(255) NOT NULL,
    phone         VARCHAR2(20),
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    active        NUMBER(1)  DEFAULT 1 NOT NULL,
    username      VARCHAR2(100),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1)  DEFAULT 0 NOT NULL,

    CONSTRAINT uq_parent_email UNIQUE (email),
    CONSTRAINT uq_parent_username UNIQUE (username)
);

CREATE TABLE classroom
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  NUMBER        NOT NULL,
    name       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_classroom_parent FOREIGN KEY (parent_id) REFERENCES parent (id)
);

CREATE TABLE student
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     NUMBER        NOT NULL,
    full_name     VARCHAR2(255) NOT NULL,
    classroom_id  NUMBER        NOT NULL,
    username      VARCHAR2(100) NOT NULL,
    password      VARCHAR2(255) NOT NULL,
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_student_username UNIQUE (username),
    CONSTRAINT fk_student_parent FOREIGN KEY (parent_id) REFERENCES parent (id),
    CONSTRAINT fk_student_classroom FOREIGN KEY (classroom_id) REFERENCES classroom (id)
);

CREATE TABLE subject
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id NUMBER        NOT NULL,
    name         VARCHAR2(255) NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    created_by   VARCHAR2(100),
    updated_by   VARCHAR2(100),
    deleted      NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_subject_classroom FOREIGN KEY (classroom_id) REFERENCES classroom (id)
);

CREATE TABLE lesson
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id    NUMBER        NOT NULL,
    name          VARCHAR2(255) NOT NULL,
    summary       CLOB,
    content       CLOB,
    textbook_page NUMBER,
    image_path    VARCHAR2(255),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_lesson_subject FOREIGN KEY (subject_id) REFERENCES subject (id)
);

CREATE TABLE question
(
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id            NUMBER        NOT NULL,
    content              CLOB          NOT NULL,
    knowledge_tag        VARCHAR2(255),
    audio_path           VARCHAR2(255),
    hide_content_in_test NUMBER(1) DEFAULT 0 NOT NULL,
    question_type        VARCHAR2(20) DEFAULT 'MULTIPLE_CHOICE' NOT NULL,
    answer_mode          VARCHAR2(20) DEFAULT 'AUDIO',
    reference_answer     CLOB,
    video_path           VARCHAR2(255),
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    created_by           VARCHAR2(100),
    updated_by           VARCHAR2(100),
    deleted              NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_question_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id)
);

CREATE TABLE choice
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER    NOT NULL,
    content     CLOB      NOT NULL,
    correct     NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_choice_question FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE test
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  NUMBER        NOT NULL,
    student_id NUMBER        NOT NULL,
    name       VARCHAR2(255) NOT NULL,
    status     VARCHAR2(20)  NOT NULL,
    test_type  VARCHAR2(20) DEFAULT 'REGULAR' NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_test_parent FOREIGN KEY (parent_id) REFERENCES parent (id),
    CONSTRAINT fk_test_student FOREIGN KEY (student_id) REFERENCES student (id)
);

CREATE TABLE test_question
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id     NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    order_index NUMBER NOT NULL,

    CONSTRAINT fk_test_question_test FOREIGN KEY (test_id) REFERENCES test (id),
    CONSTRAINT fk_test_question_question FOREIGN KEY (question_id) REFERENCES question (id)
);

CREATE TABLE attempt
(
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id         NUMBER NOT NULL,
    student_id      NUMBER NOT NULL,
    started_at      TIMESTAMP,
    submitted_at    TIMESTAMP,
    correct_count   NUMBER,
    total_questions NUMBER,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    created_by      VARCHAR2(100),
    updated_by      VARCHAR2(100),
    deleted         NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_attempt_test_id UNIQUE (test_id),
    CONSTRAINT fk_attempt_test FOREIGN KEY (test_id) REFERENCES test (id),
    CONSTRAINT fk_attempt_student FOREIGN KEY (student_id) REFERENCES student (id)
);

CREATE TABLE attempt_answer
(
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id            NUMBER NOT NULL,
    question_id           NUMBER NOT NULL,
    choice_id             NUMBER,
    correct               NUMBER(1),
    answer_audio_path     VARCHAR2(255),
    parent_marked_correct NUMBER(1),
    answer_text           CLOB,

    CONSTRAINT fk_attempt_answer_attempt FOREIGN KEY (attempt_id) REFERENCES attempt (id),
    CONSTRAINT fk_attempt_answer_question FOREIGN KEY (question_id) REFERENCES question (id),
    CONSTRAINT fk_attempt_answer_choice FOREIGN KEY (choice_id) REFERENCES choice (id)
);

CREATE TABLE refresh_token
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    NUMBER        NOT NULL,
    role       VARCHAR2(20)  NOT NULL,
    token_hash VARCHAR2(128) NOT NULL,
    expires_at TIMESTAMP     NOT NULL,
    revoked    NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_user ON refresh_token (user_id, role);

CREATE TABLE admin
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(255) NOT NULL,
    password      VARCHAR2(255) NOT NULL,
    full_name     VARCHAR2(255) NOT NULL,
    token_version NUMBER(10) DEFAULT 0 NOT NULL,
    root          NUMBER(1)  DEFAULT 0 NOT NULL,
    username      VARCHAR2(100),
    phone         VARCHAR2(20),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1)  DEFAULT 0 NOT NULL,

    CONSTRAINT uq_admin_email UNIQUE (email),
    CONSTRAINT uq_admin_username UNIQUE (username)
);

CREATE TABLE library_document
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade        NUMBER(2)     NOT NULL,
    subject_name VARCHAR2(255) NOT NULL,
    curriculum   VARCHAR2(100) NOT NULL,
    volume       VARCHAR2(100),
    title        VARCHAR2(255) NOT NULL,
    file_path    VARCHAR2(255) NOT NULL,
    file_size    NUMBER(19)    NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    created_by   VARCHAR2(100),
    updated_by   VARCHAR2(100),
    deleted      NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE subject_library_link
(
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id          NUMBER NOT NULL,
    library_document_id NUMBER NOT NULL,
    linked_at           TIMESTAMP,
    linked_by           VARCHAR2(100),

    CONSTRAINT uq_subject_library_link UNIQUE (subject_id, library_document_id),
    CONSTRAINT fk_subject_library_link_subject FOREIGN KEY (subject_id) REFERENCES subject (id),
    CONSTRAINT fk_subject_library_link_document FOREIGN KEY (library_document_id) REFERENCES library_document (id)
);
