-- Admin-managed "bo sach" (curriculum) lookup list (2026-09-05), replacing the previously
-- hardcoded 3-value list validated in LibraryService#upload. LibraryDocument.curriculum keeps
-- storing the plain name (not a foreign key - see Curriculum.java's javadoc), so no change is
-- needed to that column or any existing row. Starts empty - the old 3 names are NOT auto-seeded,
-- per the user's explicit choice (AskUserQuestion 2026-09-05: "Khong, de trong, Admin tu them").
CREATE TABLE curriculum
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_curriculum_name UNIQUE (name)
);
