CREATE TABLE parent
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name  VARCHAR2(255) NOT NULL,
    email      VARCHAR2(255) NOT NULL,
    password   VARCHAR2(255) NOT NULL,
    phone      VARCHAR2(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_parent_email UNIQUE (email)
);

CREATE TABLE student
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  NUMBER        NOT NULL,
    full_name  VARCHAR2(255) NOT NULL,
    grade      VARCHAR2(50),
    username   VARCHAR2(100) NOT NULL,
    password   VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT uq_student_username UNIQUE (username),
    CONSTRAINT fk_student_parent FOREIGN KEY (parent_id) REFERENCES parent (id)
);
