-- See postgresql/V2__lesson_attachment.sql for the feature description.
CREATE TABLE lesson_attachment
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id     NUMBER        NOT NULL,
    original_name VARCHAR2(255) NOT NULL,
    file_path     VARCHAR2(255) NOT NULL,
    file_size     NUMBER(19)    NOT NULL,
    content_type  VARCHAR2(100) NOT NULL,
    created_at    TIMESTAMP,
    created_by    VARCHAR2(100),

    CONSTRAINT fk_lesson_attachment_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id)
);
CREATE INDEX idx_lesson_attachment_lesson ON lesson_attachment (lesson_id);
