-- See postgresql/V3__library_document_multi_file.sql for the feature description.
ALTER TABLE library_document MODIFY (grade NULL);
ALTER TABLE library_document MODIFY (curriculum NULL);
ALTER TABLE library_document DROP COLUMN file_path;
ALTER TABLE library_document DROP COLUMN file_size;

CREATE TABLE library_document_file
(
    id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_document_id  NUMBER        NOT NULL,
    original_name        VARCHAR2(255) NOT NULL,
    file_path            VARCHAR2(255) NOT NULL,
    file_size            NUMBER(19)    NOT NULL,
    content_type         VARCHAR2(100) NOT NULL,
    uploaded_at          TIMESTAMP,
    uploaded_by          VARCHAR2(100),

    CONSTRAINT fk_library_document_file_document FOREIGN KEY (library_document_id) REFERENCES library_document (id)
);
CREATE INDEX idx_library_document_file_document ON library_document_file (library_document_id);
