CREATE TABLE subject
(
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroom_id NUMBER        NOT NULL,
    name         VARCHAR2(255) NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    created_by   VARCHAR2(100),
    updated_by   VARCHAR2(100),
    deleted      NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_subject_classroom FOREIGN KEY (classroom_id) REFERENCES classroom (id)
);

CREATE TABLE lesson
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id NUMBER        NOT NULL,
    name       VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_lesson_subject FOREIGN KEY (subject_id) REFERENCES subject (id)
);
