CREATE TABLE question
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id     NUMBER        NOT NULL,
    content       CLOB          NOT NULL,
    knowledge_tag VARCHAR2(255),
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    created_by    VARCHAR2(100),
    updated_by    VARCHAR2(100),
    deleted       NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_question_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id)
);

CREATE TABLE choice
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id NUMBER    NOT NULL,
    content     CLOB      NOT NULL,
    correct     NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_choice_question FOREIGN KEY (question_id) REFERENCES question (id)
);
