CREATE TABLE test
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id  NUMBER        NOT NULL,
    student_id NUMBER        NOT NULL,
    name       VARCHAR2(255) NOT NULL,
    status     VARCHAR2(20)  NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR2(100),
    updated_by VARCHAR2(100),
    deleted    NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_test_parent FOREIGN KEY (parent_id) REFERENCES parent (id),
    CONSTRAINT fk_test_student FOREIGN KEY (student_id) REFERENCES student (id)
);

CREATE TABLE test_question
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id     NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    order_index NUMBER NOT NULL,

    CONSTRAINT fk_test_question_test FOREIGN KEY (test_id) REFERENCES test (id),
    CONSTRAINT fk_test_question_question FOREIGN KEY (question_id) REFERENCES question (id)
);
