CREATE TABLE attempt
(
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_id          NUMBER NOT NULL,
    student_id       NUMBER NOT NULL,
    started_at       TIMESTAMP,
    submitted_at     TIMESTAMP,
    correct_count    NUMBER,
    total_questions  NUMBER,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    created_by       VARCHAR2(100),
    updated_by       VARCHAR2(100),
    deleted          NUMBER(1) DEFAULT 0 NOT NULL,

    CONSTRAINT fk_attempt_test FOREIGN KEY (test_id) REFERENCES test (id),
    CONSTRAINT fk_attempt_student FOREIGN KEY (student_id) REFERENCES student (id)
);

CREATE TABLE attempt_answer
(
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  NUMBER NOT NULL,
    question_id NUMBER NOT NULL,
    choice_id   NUMBER,
    correct     NUMBER(1),

    CONSTRAINT fk_attempt_answer_attempt FOREIGN KEY (attempt_id) REFERENCES attempt (id),
    CONSTRAINT fk_attempt_answer_question FOREIGN KEY (question_id) REFERENCES question (id),
    CONSTRAINT fk_attempt_answer_choice FOREIGN KEY (choice_id) REFERENCES choice (id)
);
